---
abstract: 'Perl extension for breaking text paragraphs into sentences'
author:
  - 'Achim Ruopp, <achimru@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Sentence
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Carp: 0
  File::ShareDir: 1.02
  perl: 5.8.8
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 1.04
